server:
  port: 8095
spring:
  application:
    name: datum-srv-status-publisher
  rabbitmq:
    host: ${RMQ_HOST:localhost}
    port: ${RMQ_PORT:5672}
    virtual-host: ${RMQ_VIRTUAL_HOST:/}
    username: ${RMQ_USERNAME:guest}
    password: ${RMQ_PASSWORD:guest}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${AUTH_HOST:localhost}:${AUTH_PORT:9000}

datum:
  rabbitmq:
    customer-status-change-queue: customer_status_changed
